export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export enum ACTION_TYPES  {
    GET_ITEMS = "GET_ITEMS",
    ADD_ITEM = "ADD_ITEM",
    DELETE_ITEM = "DELETE_ITEM",
    EDIT_ITEM = "EDIT_ITEM",
    ITEMS_LOADING = "ITEMS_LOADING",
}

export enum ERROR_ACTION_TYPES  {
    GET_ERRORS = "GET_ERRORS",
    CLEAR_ERRORS = "CLEAR_ERRORS",
}

export enum PROCEDURE_ACTION_TYPES {
    CHOOSE_LANGUAGE = "CHOOSE_LANGUAGE",
    CHOOSE_PROCEDURE = "CHOOSE_PROCEDURE",
    SELECT_CHECKLIST_ITEM = "SELECT_CHECKLIST_ITEM",
}

